from typing import Any

class FrontMatter:
    @property
    def kind(self) -> str: ...
    @property
    def raw(self) -> str: ...

class RenderPlan:
    @property
    def image_checksums(self) -> list[str]: ...
    @property
    def toc(self) -> list[dict[str, Any]]: ...
    @property
    def frontmatter(self) -> FrontMatter | None: ...
    def finish(self, images: dict[str, dict[str, Any]] | None = None) -> str: ...

class MarkdownIt:
    def __init__(self) -> None: ...
    def prepare(
        self,
        src: str,
        *,
        include_toc: bool = False,
        include_frontmatter: bool = False,
    ) -> RenderPlan: ...
