#!/bin/sh
set -eu

: "${DATABASE_NAME:?DATABASE_NAME is required}"
: "${DATABASE_USER:?DATABASE_USER is required}"
: "${DATABASE_PASSWORD:?DATABASE_PASSWORD is required}"

PGBOUNCER_BACKEND_HOST="${PGBOUNCER_BACKEND_HOST:-blog-postgres}"
PGBOUNCER_BACKEND_PORT="${PGBOUNCER_BACKEND_PORT:-5432}"
PGBOUNCER_LISTEN_ADDR="${PGBOUNCER_LISTEN_ADDR:-0.0.0.0}"
PGBOUNCER_LISTEN_PORT="${PGBOUNCER_LISTEN_PORT:-6432}"
PGBOUNCER_POOL_MODE="${PGBOUNCER_POOL_MODE:-transaction}"
PGBOUNCER_MAX_CLIENT_CONN="${PGBOUNCER_MAX_CLIENT_CONN:-500}"
PGBOUNCER_DEFAULT_POOL_SIZE="${PGBOUNCER_DEFAULT_POOL_SIZE:-20}"
PGBOUNCER_RESERVE_POOL_SIZE="${PGBOUNCER_RESERVE_POOL_SIZE:-5}"
PGBOUNCER_RESERVE_POOL_TIMEOUT="${PGBOUNCER_RESERVE_POOL_TIMEOUT:-5}"
PGBOUNCER_MAX_DB_CONNECTIONS="${PGBOUNCER_MAX_DB_CONNECTIONS:-40}"
PGBOUNCER_SERVER_IDLE_TIMEOUT="${PGBOUNCER_SERVER_IDLE_TIMEOUT:-60}"
PGBOUNCER_SERVER_LIFETIME="${PGBOUNCER_SERVER_LIFETIME:-3600}"
PGBOUNCER_QUERY_WAIT_TIMEOUT="${PGBOUNCER_QUERY_WAIT_TIMEOUT:-30}"
PGBOUNCER_LOG_CONNECTIONS="${PGBOUNCER_LOG_CONNECTIONS:-0}"
PGBOUNCER_LOG_DISCONNECTIONS="${PGBOUNCER_LOG_DISCONNECTIONS:-0}"
PGBOUNCER_LOG_STATS="${PGBOUNCER_LOG_STATS:-1}"
PGBOUNCER_STATS_PERIOD="${PGBOUNCER_STATS_PERIOD:-60}"

cat > /tmp/userlist.txt <<EOF
"${DATABASE_USER}" "${DATABASE_PASSWORD}"
EOF

cat > /tmp/pgbouncer.ini <<EOF
[databases]
${DATABASE_NAME} = host=${PGBOUNCER_BACKEND_HOST} port=${PGBOUNCER_BACKEND_PORT} dbname=${DATABASE_NAME}

[pgbouncer]
listen_addr = ${PGBOUNCER_LISTEN_ADDR}
listen_port = ${PGBOUNCER_LISTEN_PORT}
auth_type = plain
auth_file = /tmp/userlist.txt
pool_mode = ${PGBOUNCER_POOL_MODE}
max_client_conn = ${PGBOUNCER_MAX_CLIENT_CONN}
default_pool_size = ${PGBOUNCER_DEFAULT_POOL_SIZE}
reserve_pool_size = ${PGBOUNCER_RESERVE_POOL_SIZE}
reserve_pool_timeout = ${PGBOUNCER_RESERVE_POOL_TIMEOUT}
max_db_connections = ${PGBOUNCER_MAX_DB_CONNECTIONS}
server_idle_timeout = ${PGBOUNCER_SERVER_IDLE_TIMEOUT}
server_lifetime = ${PGBOUNCER_SERVER_LIFETIME}
query_wait_timeout = ${PGBOUNCER_QUERY_WAIT_TIMEOUT}
ignore_startup_parameters = extra_float_digits
admin_users = ${DATABASE_USER}
stats_users = ${DATABASE_USER}
log_connections = ${PGBOUNCER_LOG_CONNECTIONS}
log_disconnections = ${PGBOUNCER_LOG_DISCONNECTIONS}
log_stats = ${PGBOUNCER_LOG_STATS}
stats_period = ${PGBOUNCER_STATS_PERIOD}
EOF

exec pgbouncer /tmp/pgbouncer.ini
