[package]
name = "markdown-it-rs-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "markdown_it_rs_py"
crate-type = ["cdylib"]

[dependencies]
markdown-it-rs = { path = "upstream", default-features = false, features = [
    "linkify",
    "syntect",
    "katex",
] }
pyo3 = { version = "0.29", features = ["extension-module"] }
