# Generated by Django 6.0.4 on 2026-05-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageresource",
            name="placeholder",
            field=models.TextField(blank=True, default=""),
        ),
    ]
