# Generated by Django 6.0.6 on 2026-07-11 14:23

import django.db.models.deletion
import media_service.models.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_service", "0002_imageresource_placeholder"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageresource",
            name="responsive_variants_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ImageVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ImageField(
                        upload_to=media_service.models.image.image_variant_update_path
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("avif", "AVIF"), ("webp", "WEBP")], max_length=8
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("size", models.PositiveIntegerField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="media_service.imageresource",
                    ),
                ),
            ],
            options={
                "ordering": ["format", "width"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "format", "width"),
                        name="unique_image_responsive_variant",
                    )
                ],
            },
        ),
    ]
