# k8s/overlays/prod/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-litellm-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "100"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - $BACKEND_DOMAIN
      secretName: blog-django-tls-secret
  rules:
    - host: $BACKEND_DOMAIN
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: blog-litellm
                port:
                  number: 4000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    # the entry point used by the route (WebSecure corresponds to HTTPS port 443).
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # enable TLS encryption
    traefik.ingress.kubernetes.io/router.tls: "true"
    # keep the catch-all route below the protected /prometheus router
    traefik.ingress.kubernetes.io/router.priority: "1"
    # rate limiting
    traefik.ingress.kubernetes.io/ratelimit.average: "1000"
    # certificate management
    # install cert-manager first, https://cert-manager.io/docs/installation/
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - $BACKEND_DOMAIN
      secretName: blog-django-tls-secret
  rules:
    - host: $BACKEND_DOMAIN
      http:
        paths:
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: blog-django
                port:
                  name: static
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-django
                port:
                  name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-prometheus-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.middlewares: blog-prometheus-whitelist@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
    - host: $BACKEND_DOMAIN
      http:
        paths:
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: blog-django
                port:
                  number: 8000
