apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog

resources:
- ../../base
- ingress.yaml
- cluster-issuer.yaml
- middleware-whitelist.yaml
- middleware-scanner-block.yaml

# In prod, images are managed by Woodpecker CI & Argo CD
images:
- name: blog-app
  newName: registry.gsgfs.sh/blog-app
  newTag: f12d57b4208d57e3452ce55e14f8d6fcde47ddd9
- name: blog-backup
  newName: registry.gsgfs.sh/blog-backup
  newTag: f12d57b4208d57e3452ce55e14f8d6fcde47ddd9
- name: blog-model-downloader
  newName: registry.gsgfs.sh/blog-model-downloader
  newTag: f12d57b4208d57e3452ce55e14f8d6fcde47ddd9
- name: blog-pgbouncer
  newName: registry.gsgfs.sh/blog-pgbouncer
  newTag: f12d57b4208d57e3452ce55e14f8d6fcde47ddd9
