apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog

resources:
- ../../base
- ingress.yaml
- cluster-issuer.yaml
- middleware-whitelist.yaml
- middleware-scanner-block.yaml

# In prod, images are managed by Woodpecker CI & Argo CD
images:
- name: blog-app
  newName: registry.gsgfs.sh/blog-app
  newTag: 1b22951f79970f736e8f0846c439dd06743c694d
- name: blog-backup
  newName: registry.gsgfs.sh/blog-backup
  newTag: 1b22951f79970f736e8f0846c439dd06743c694d
- name: blog-model-downloader
  newName: registry.gsgfs.sh/blog-model-downloader
  newTag: 1b22951f79970f736e8f0846c439dd06743c694d
- name: blog-pgbouncer
  newName: registry.gsgfs.sh/blog-pgbouncer
  newTag: 1b22951f79970f736e8f0846c439dd06743c694d
