apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog

resources:
- ../../base
- ingress.yaml
- cluster-issuer.yaml
- middleware-whitelist.yaml

# In prod, images are managed by Woodpecker CI & Argo CD
images:
- name: blog-app
  newName: registry.gsgfs.sh/blog-app
  newTag: 4cedca7a5e1061aea5e0b9637806baad17b56a4e
- name: blog-backup
  newName: registry.gsgfs.sh/blog-backup
  newTag: 4cedca7a5e1061aea5e0b9637806baad17b56a4e
- name: blog-model-downloader
  newName: registry.gsgfs.sh/blog-model-downloader
  newTag: 4cedca7a5e1061aea5e0b9637806baad17b56a4e
