# Generated by Django 6.0.5 on 2026-05-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_remove_image_resource_remove_image_uploaded_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="toc",
            field=models.JSONField(blank=True, help_text="文章目录", null=True),
        ),
    ]
