# Generated by Django 6.0.5 on 2026-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_post_toc"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="layout",
            field=models.CharField(
                choices=[("article", "文章"), ("poem", "诗")],
                default="article",
                max_length=20,
            ),
        ),
    ]
