# Generated by Django 6.0.5 on 2026-06-10 14:57

import core.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_post_layout"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_id", models.CharField(max_length=64, unique=True)),
                ("secret", core.field.FernetField(blank=True, default="")),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client_id"], name="api_apiclie_client__4f77a3_idx"
                    )
                ],
            },
        ),
    ]
