# Generated by Django 6.0.6 on 2026-06-30 10:08

import core.field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_backfill_post_published_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("authorization_url", models.URLField(max_length=500)),
                ("token_url", models.URLField(max_length=500)),
                ("userinfo_url", models.URLField(max_length=500)),
                ("scope", models.CharField(default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "OAuth Provider",
                "verbose_name_plural": "OAuth Providers",
            },
        ),
        migrations.RemoveField(
            model_name="guest",
            name="password",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="provider_id",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="unique_id",
        ),
        migrations.CreateModel(
            name="OAuthIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(max_length=128)),
                ("access_token", core.field.FernetField(blank=True, default="")),
                ("refresh_token", core.field.FernetField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_identities",
                        to="api.guest",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_identities",
                        to="api.oauthprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth Identity",
                "verbose_name_plural": "OAuth Identities",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "user_id"),
                        name="unique_oauth_provider_user",
                    )
                ],
            },
        ),
    ]
