# Generated by Django 6.0.7 on 2026-07-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_oauthprovider_remove_guest_password_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "get_latest_by": ["published_at", "created_at"],
                "ordering": ["-order", "-created_at"],
            },
        ),
    ]
