# Generated by Django 6.0.8 on 2026-10-04 01:50

import core.field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_alter_post_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiClientCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kid",
                    models.CharField(
                        editable=False, help_text="key ID", max_length=32, unique=True
                    ),
                ),
                ("secret", core.field.FernetField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="apiclient",
            name="api_apiclie_client__4f77a3_idx",
        ),
        migrations.AddField(
            model_name="apiclientcredential",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="api.apiclient",
            ),
        ),
        migrations.RemoveField(
            model_name="apiclient",
            name="secret",
        ),
    ]
