LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "admin:index"

OTP_LOGIN_URL = LOGIN_URL
OTP_TOTP_ISSUER = "GSGFs's blog"
OTP_ADMIN_HIDE_SENSITIVE_DATA = True

TWO_FACTOR_PREAUTH_TTL = 300
TWO_FACTOR_RECOVERY_CODE_COUNT = 10

LOGIN_THROTTLE_WINDOW = 300
LOGIN_THROTTLE_ACCOUNT_LIMIT = 5
LOGIN_THROTTLE_ADDRESS_LIMIT = 25
