"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

Default: https://github.com/django/django/blob/main/django/conf/global_settings.py
"""

import logging
import os
from pathlib import Path
from typing import List

from django.utils.csp import CSP
from dotenv import load_dotenv


# 用于规范化的辅助函数
def _split_csv(env_str: str) -> List[str]:
    return [x.strip() for x in env_str.split(",") if x and x.strip()]


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in ("1", "true", "yes", "on")


def _env_int(name: str, default: int) -> int:
    value = os.environ.get(name)
    if value is None:
        return default
    return int(value)


def is_docker_env() -> bool:
    return _env_bool("DOCKER_ENV")


def is_k8s_env() -> bool:
    """Check if running in Kubernetes environment"""
    return _env_bool("K8S_ENV")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 载入 .env 就算没有也不会出问题
load_dotenv(os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default="False") == "True")
SOLID_ISLANDS_SSR = _env_bool("SOLID_ISLANDS_SSR", not DEBUG)

APP_BUILD_ID = os.environ.get("APP_BUILD_ID", "").strip()
if not APP_BUILD_ID:
    if not DEBUG:
        raise RuntimeError("APP_BUILD_ID is required when DEBUG is disabled")
    APP_BUILD_ID = "local"

# 在 K8s 环境中允许所有 hosts 以支持 Pod IP 健康检查
if is_k8s_env():
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = _split_csv(
        os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1, localhost")
    )

# CDN 和代理配置
USE_X_FORWARDED_HOST = True  # 信任头部设置
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# csrf配置
CSRF_TRUSTED_ORIGINS = (
    _split_csv(os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", ""))
    if os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS")
    else []
)

# 安全设置
# 在 K8s 环境中禁用 SSL 重定向以支持内部健康检查
SECURE_SSL_REDIRECT = not DEBUG and not is_k8s_env()  # 强制 HTTPS (生产环境且非 K8s)
SESSION_COOKIE_SECURE = not DEBUG  # 仅通过 HTTPS 发送 cookie
CSRF_COOKIE_SECURE = not DEBUG  # 仅通过 HTTPS 发送 CSRF cookie
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# CSP
_static_src = "https://static.gsgfs.moe"
_img_src = "https://img.gsgfs.moe"
_vite_src = "http://localhost:5173"
_vite_ws_src = "ws://localhost:5173"
IMAGE_PICTURE_URL_PREFIXES = {
    f"{_img_src}/images/raw/": {
        "avif": f"{_img_src}/images/avif/",
        "webp": f"{_img_src}/images/webp/",
    }
}
CSP_POLICY = {
    "default-src": [CSP.SELF, _img_src],  # prefetch imgs
    "base-uri": [CSP.NONE],
    "object-src": [CSP.NONE],
    "frame-src": [CSP.NONE],
    "frame-ancestors": [CSP.NONE],
    "form-action": [CSP.SELF],
    "script-src": [CSP.SELF, CSP.WASM_UNSAFE_EVAL, _static_src],
    "script-src-attr": [CSP.NONE],
    # xterm.js needs inline style
    "style-src": [CSP.SELF, CSP.UNSAFE_INLINE, _static_src],
    "style-src-attr": [CSP.UNSAFE_INLINE],
    "img-src": [CSP.SELF, "data:", "blob:", _img_src, _static_src],
    "font-src": [CSP.SELF, "data:", _static_src],
    "connect-src": [CSP.SELF, _static_src],
    "worker-src": [CSP.SELF, "blob:", _static_src],
    "media-src": [CSP.SELF],
    "manifest-src": [CSP.SELF],
}
if DEBUG:
    CSP_POLICY["script-src"].append(_vite_src)
    CSP_POLICY["style-src"].append(_vite_src)
    CSP_POLICY["font-src"].append(_vite_src)
    CSP_POLICY["connect-src"].extend([_vite_src, _vite_ws_src])
else:
    CSP_POLICY["upgrade-insecure-requests"] = True

SECURE_CSP = CSP_POLICY

# CF's bot fighter
CLOUDFLARE_JSD_ENABLED = _env_bool(
    "CLOUDFLARE_JSD_ENABLED",
    not DEBUG,
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.postgres",
    "django.contrib.admin",
    "django.contrib.auth",  # 验证框架和默认模型
    "django.contrib.sitemaps",
    "django.contrib.contenttypes",  # 内容类型框架
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ninja",
    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp.plugins.otp_totp",
    "two_factor",
    "django_celery_beat",  # Celery 定时任务
    "django_prometheus",  # 监控
    "api.apps.ApiConfig",
    "media_service.apps.MediaServiceConfig",
    "web.apps.WebConfig",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "web.middleware.HeadersMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "web.middleware.HtmxMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "blog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # 设置模板的搜索路径
        "APP_DIRS": not DEBUG,
        "OPTIONS": {
            # disable template cache in DEBUG
            **(
                {
                    "loaders": [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ]
                }
                if DEBUG
                else {}
            ),
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "web.context_processors.site_meta",
            ],
        },
    },
]

WSGI_APPLICATION = "blog.wsgi.application"
ASGI_APPLICATION = "blog.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# A problem that has been solved
# Cascade failure causes database connection to be closed
_database_engine = os.getenv("DATABASE_ENGINE", "postgresql")
if not _database_engine:
    # Build-time or local development fallback
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django_prometheus.db.backends.{}".format(_database_engine),
            "NAME": os.getenv("DATABASE_NAME"),
            "USER": os.getenv("DATABASE_USER"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD"),
            "HOST": os.getenv(
                "DATABASE_HOST",
                "blog-postgres" if is_docker_env() else "127.0.0.1",
            ),
            "PORT": os.getenv("DATABASE_PORT", 5432),
            "CONN_MAX_AGE": _env_int("DATABASE_CONN_MAX_AGE", 0),
            "CONN_HEALTH_CHECKS": _env_bool("DATABASE_CONN_HEALTH_CHECKS", True),
            "DISABLE_SERVER_SIDE_CURSORS": _env_bool("DATABASE_USE_PGBOUNCER"),
        }
    }

_redis_host = os.environ.get("REDIS_HOST", "localhost")
# 如果是 docker 环境强制使用 "blog-redis" 作为 host, 这是在 docker 配置中写死了的
if is_docker_env():
    _redis_host = "blog-redis"
_redis_port = os.environ.get("REDIS_PORT", "6379")
# 使用0号数据库
_redis_url = os.environ.get("REDIS_URL", f"redis://{_redis_host}:{_redis_port}/0")

CACHES = {
    "default": {
        "BACKEND": "django_prometheus.cache.backends.redis.RedisCache",
        "LOCATION": _redis_url,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
        },
        "KEY_PREFIX": "django",  # eg. django:1:health_check
    },
    # this alias ignore exceptions
    "image_metadata": {
        "BACKEND": "django_prometheus.cache.backends.redis.RedisCache",
        "LOCATION": _redis_url,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": "image-metadata",
    },
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"  # 设置session使用缓存
SESSION_CACHE_ALIAS = "default"
CACHE_TTL = 60 * 10  # 缓存超时时间

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = os.getenv("STATIC_URL", "/static/")
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# python manage.py collectstatic --noinput 收集静态文件

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# img bed
USE_S3 = os.getenv("USE_S3", "False").lower() in ("true", "yes", "1", "on")
S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")
S3_ENDPOINT_URL = os.getenv("S3_ENDPOINT_URL")
S3_ACCESS_KEY_ID = os.getenv("S3_ACCESS_KEY_ID")
S3_SECRET_ACCESS_KEY = os.getenv("S3_SECRET_ACCESS_KEY")
S3_PUBLIC_DOMAIN = os.getenv("S3_PUBLIC_DOMAIN")


def _storage_backend():
    if not USE_S3:
        return {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        }

    if not all(
        [S3_BUCKET_NAME, S3_ENDPOINT_URL, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY]
    ):
        raise RuntimeError("S3 storage is not fully configured")

    options = {
        "bucket_name": S3_BUCKET_NAME,
        "endpoint_url": S3_ENDPOINT_URL,
        "access_key": S3_ACCESS_KEY_ID,
        "secret_key": S3_SECRET_ACCESS_KEY,
        "querystring_auth": False,  # public bucket
    }
    if S3_PUBLIC_DOMAIN:
        options["custom_domain"] = S3_PUBLIC_DOMAIN

    return {
        "BACKEND": "media_service.backends.MediaStorage",
        "OPTIONS": options,
    }


IMAGE_UPLOAD_MAX_SIZE = 20971520  # 20MiB
DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20MiB

STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
    "default": _storage_backend(),
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

API_KEY = os.getenv("API_KEY")
if API_KEY is None:
    logging.warning("API_KEY is not set in environment variables.")
FERNET_KEY = os.getenv("FERNET_KEY")
if FERNET_KEY is None:
    logging.warning("FERNET_KEY is not set in environment variables.")
FERNET_OLD_KEYS = _split_csv(os.getenv("FERNET_OLD_KEYS", ""))

RESEND_API_KEY = os.getenv("RESEND_API_KEY")

LOGIN_URL = "two_factor:login"

# this one is optional
LOGIN_REDIRECT_URL = "two_factor:profile"

# email backend
EMAIL_BACKEND = "api.backends.ResendEmailBackend"  # 从 __init__.py 中获取
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")  # Address sent to website administrator
ADMINS = [("admin", os.getenv("ADMIN_EMAIL"))]

# logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.environ.get("DJANGO_LOGLEVEL", "INFO").upper(),
    },
}

# Celery configuration
CELERY_BROKER_URL = _redis_url
CELERY_RESULT_BACKEND = _redis_url
CELERY_TIMEZONE = "Asia/Shanghai"
# Celery scheduled tasks use database storage,
# if not it django_celery_beat will not work
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Django-ninja
NINJA_PAGINATION_CLASS = "api.pagination.Pagination"

# vector search
MODEL_NAME = os.environ.get("MODEL_NAME")
SENTENCE_TRANSFORMERS_HOME = os.environ.get("SENTENCE_TRANSFORMERS_HOME")

# LiteLLM
REMOTE_EMBEDDING_API_BASE = os.environ.get(
    "REMOTE_EMBEDDING_API_BASE", "http://blog-litellm:4000/v1"
)
REMOTE_EMBEDDING_API_KEY = os.environ.get("REMOTE_EMBEDDING_API_KEY", "sk-1234")
REMOTE_EMBEDDING_MODEL_NAME = os.environ.get(
    "REMOTE_EMBEDDING_MODEL_NAME", "embeddinggemma-300m"
)
USE_REMOTE_EMBEDDING = os.environ.get("USE_REMOTE_EMBEDDING", "False").lower() in (
    "1",
    "true",
    "yes",
)

# supervisord may use root permissions
# PermissionError: [Errno 13] Permission denied: '/root/.cache/huggingface/token'
if SENTENCE_TRANSFORMERS_HOME:
    os.environ["HF_HOME"] = SENTENCE_TRANSFORMERS_HOME
    # 'local_files_only=True'
    # This setting only prevents the download of model weights.
    # But 'transformers' or 'huggingface_hub' may still attempt to connect to network
    os.environ["HF_HUB_OFFLINE"] = "1"

# Test runner configuration
# Use custom QuietTestRunner to suppress noisy log output during tests
TEST_RUNNER = "api.tests.runner.QuietTestRunner"
# Disable hugging face process bar
os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"

# DEBUG settings
# if DEBUG:
#     try:
#         import debug_toolbar  # noqa
#     except ImportError:
#         pass
#     else:
#         # django-debug-toolbar
#         INSTALLED_APPS.append(
#             "debug_toolbar",
#         )
#         MIDDLEWARE.insert(
#             MIDDLEWARE.index("web.middleware.HtmxMiddleware"),
#             "debug_toolbar.middleware.DebugToolbarMiddleware",
#         )
#         INTERNAL_IPS = [
#             "127.0.0.1",
#         ]
