# k8s/base/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  DEBUG: "False"
  DJANGO_LOGLEVEL: "info"
  DJANGO_ALLOWED_HOSTS: "*"
  DATABASE_ENGINE: "postgresql"
  DATABASE_NAME: "blog"
  DATABASE_HOST: "blog-postgres"
  DATABASE_PORT: "5432"
  DATABASE_CONN_MAX_AGE: "0"
  DATABASE_CONN_HEALTH_CHECKS: "True"
  # override here in app side if it needs pgbouncer
  DATABASE_USE_PGBOUNCER: "False"
  PGBOUNCER_POOL_MODE: "transaction"
  PGBOUNCER_MAX_CLIENT_CONN: "1000"
  PGBOUNCER_DEFAULT_POOL_SIZE: "40"
  PGBOUNCER_RESERVE_POOL_SIZE: "10"
  PGBOUNCER_MAX_DB_CONNECTIONS: "80"
  PGBOUNCER_QUERY_WAIT_TIMEOUT: "10"
  REDIS_HOST: "blog-redis"
  REDIS_PORT: "6379"
  USE_S3: "True"
  USE_REMOTE_EMBEDDING: "True"
  MODEL_NAME: "google/embeddinggemma-300m"
  GGUF_MODEL_NAME: "ggml-org/embeddinggemma-300M-GGUF"
  SENTENCE_TRANSFORMERS_HOME: "/models"
  #HF_ENDPOINT: "https://hf-mirror.com"
  K8S_ENV: "True"
  BACKUP_BUCKET: "backup"
  PAGE_NAVIGATION_MODE: "auto"
