# k8s/base/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
data:
  DEBUG: "False"
  DJANGO_LOGLEVEL: "info"
  DJANGO_ALLOWED_HOSTS: "*"
  DATABASE_ENGINE: "postgresql"
  DATABASE_NAME: "blog"
  DATABASE_HOST: "blog-postgres"
  DATABASE_PORT: "5432"
  REDIS_HOST: "blog-redis"
  REDIS_PORT: "6379"
  USE_S3: "True"
  USE_REMOTE_EMBEDDING: "True"
  MODEL_NAME: "google/embeddinggemma-300m"
  GGUF_MODEL_NAME: "ggml-org/embeddinggemma-300M-GGUF"
  SENTENCE_TRANSFORMERS_HOME: "/models"
  #HF_ENDPOINT: "https://hf-mirror.com"
  K8S_ENV: "True"
  BACKUP_BUCKET: "backup"
