# k8s/base/job-migrate.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: blog-django-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: blog-app:latest
          command:
            - python
            - -c
            - |
              import socket, time
              addr = ('blog-postgres', 5432)
              while True:
                  try: 
                      socket.create_connection(addr, timeout=2)
                      break
                  except: 
                      print('waiting for postgres...')
                      time.sleep(2)
      volumes:
        - name: staticfiles
          emptyDir: {}
      containers:
        - name: blog-django-migrate
          image: blog-app:latest
          command:
            - python
            - manage.py
            - migrate
            - "--noinput"
          envFrom:
            - configMapRef:
                name: blog-config
            - secretRef:
                name: blog-secrets
  backoffLimit: 4
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 60 # 1min
