# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

resources:
  - namespace.yaml
  - pvc.yaml
  - postgres.yaml
  - pgbouncer.yaml
  - redis.yaml
  - django.yaml
  - celery-worker.yaml
  - celery-beat.yaml
  - job-migrate.yaml
  - job-backup.yaml
  - configmap.yaml
  - litellm.yaml
  - llama-cpp.yaml
  # use `scripts/k3s-sync-secrets.sh` to generate k8s secret
  # - secrets.yaml
