# k8s/base/postgres.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path # k3s local storage

---
apiVersion: apps/v1
kind: StatefulSet # PostgreSQL is a stateful service
metadata:
  name: blog-postgres
spec:
  serviceName: blog-postgres
  replicas: 1 # deploy only 1 replica (single-node PostgreSQL)
  selector:
    matchLabels:
      app: blog-postgres
  template:
    metadata:
      labels:
        app: blog-postgres
    spec:
      volumes:
        # associate PVC with Pod
        - name: blog-postgres-storage
          persistentVolumeClaim:
            claimName: blog-postgres-pvc
        - name: blog-postgres-config
          configMap:
            name: blog-postgres-config
      containers:
        - name: blog-postgres
          image: pgvector/pgvector:pg18-trixie
          ports:
            - containerPort: 5432
          volumeMounts:
            # mount the PVC
            - name: blog-postgres-storage
              mountPath: /var/lib/postgresql
            - name: blog-postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
          resources:
            requests:
              memory: "768Mi"
              cpu: "250m" # 1000m == 1 cpu core
            limits:
              memory: "1Gi"
              cpu: "1000m"
          args:
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: DATABASE_PASSWORD
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -h "$POD_IP" -U "$POSTGRES_USER"
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: blog-postgres
spec:
  selector:
    app: blog-postgres
  ports:
    - port: 5432 # expose by service
      targetPort: 5432 # Pod's port
  type: ClusterIP # accessible only within the cluster

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-postgres-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    shared_buffers = 256MB
    max_connections = 200
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    effective_cache_size = 768MB
    wal_buffers = 7864kB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 1260kB
    huge_pages = off
    min_wal_size = 1GB
    max_wal_size = 4GB
    log_timezone = 'Asia/Shanghai'
    timezone = 'Asia/Shanghai'
