apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GSGFs7/blog.git
    targetRevision: HEAD
    path: .config/k8s/overlays/prod
    kustomize:
      patches:
        - target:
            kind: Ingress
            name: blog-ingress
          patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: ${BACKEND_DOMAIN}
            - op: replace
              path: /spec/tls/0/hosts/0
              value: ${BACKEND_DOMAIN}
        - target:
            kind: Ingress
            name: blog-static-ingress
          patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: ${BACKEND_DOMAIN}
            - op: replace
              path: /spec/tls/0/hosts/0
              value: ${BACKEND_DOMAIN}
        - target:
            kind: Ingress
            name: blog-litellm-ingress
          patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: ${BACKEND_DOMAIN}
            - op: replace
              path: /spec/tls/0/hosts/0
              value: ${BACKEND_DOMAIN}
        - target:
            kind: Ingress
            name: blog-prometheus-ingress
          patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: ${BACKEND_DOMAIN}
            - op: add
              path: /spec/tls
              value:
                - hosts:
                    - ${BACKEND_DOMAIN}
                  secretName: blog-django-tls-secret
        - target:
            kind: ClusterIssuer
            name: letsencrypt-prod
          patch: |-
            - op: replace
              path: /spec/acme/email
              value: ${ADMIN_EMAIL}
  destination:
    server: https://kubernetes.default.svc # current cluster
    namespace: blog
  syncPolicy:
    automated:
      prune: true # Automatically delete resources that no longer exist in Git
      selfHeal: true # Automatically correct back to Git status
