#!/usr/bin/env python3
# generated by LLM

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator, Sequence
from urllib.parse import parse_qsl, quote, urlencode, urljoin, urlsplit, urlunsplit

logger = logging.getLogger(__name__)

DEFAULT_RESOURCE_HOSTS = ["img.gsgfs.moe", "static.gsgfs.moe"]
DEFAULT_EXCLUDED_PREFIXES = ["/admin", "/accounts", "/api"]
DEFAULT_EXCLUDED_PATHS = {
    "/favicon.ico",
    "/llms.txt",
    "/logout",
    "/robots.txt",
    "/sitemap.xml",
}
CACHED_STATUSES = {"HIT", "REVALIDATED", "STALE", "UPDATING"}
_URL_PATH_SAFE = "/:@!$&'()*+,;=-._~%[]|"
_URL_QUERY_SAFE = "/?:@!$&'()*+,;=%-._~[]|{}^`"


@dataclass
class AuditOptions:
    base_url: str = "https://gsgfs.moe/"
    sitemap_url: str | None = None
    output: str | None = None
    max_pages: int = 500
    timeout_ms: int = 30_000
    settle_ms: int = 1_000
    scroll_delay_ms: int = 150
    max_scrolls: int = 40
    delay_ms: int = 100
    profiles: list[str] = field(default_factory=list)
    resource_hosts: list[str] = field(default_factory=list)
    excluded_prefixes: list[str] = field(
        default_factory=lambda: list(DEFAULT_EXCLUDED_PREFIXES)
    )
    storage_state: str | None = None
    fail_on_issues: bool = False
    resource_host_set: set[str] = field(default_factory=set, init=False, repr=False)


@dataclass
class PageResult:
    url: str
    profile: str
    pass_number: int
    status: int | None = None
    content_type: str | None = None
    errors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "url": self.url,
            "profile": self.profile,
            "pass": self.pass_number,
            "status": self.status,
            "contentType": self.content_type,
            "errors": self.errors,
        }


@dataclass
class ResourceSample:
    url: str
    page_url: str
    profile: str
    pass_number: int
    resource_type: str
    http_status: int
    cache_control: str | None
    cf_cache_status: str | None
    age: str | None
    cf_ray: str | None
    content_type: str | None
    from_service_worker: bool

    def to_dict(self) -> dict:
        return {
            "url": self.url,
            "pageUrl": self.page_url,
            "profile": self.profile,
            "pass": self.pass_number,
            "resourceType": self.resource_type,
            "httpStatus": self.http_status,
            "cacheControl": self.cache_control,
            "cfCacheStatus": self.cf_cache_status,
            "age": self.age,
            "cfRay": self.cf_ray,
            "contentType": self.content_type,
            "fromServiceWorker": self.from_service_worker,
        }


@dataclass
class PageScan:
    page: PageResult
    links: list[str]
    resources: list[ResourceSample]


@dataclass
class DiscoveryResult:
    visited: list[str]
    page_results: list[PageResult]
    resources: list[ResourceSample]


@dataclass
class VerificationResult:
    page_results: list[PageResult]
    resources: list[ResourceSample]


@dataclass
class AggregatedResource:
    url: str
    hostname: str
    pages: list[str]
    profiles: list[str]
    resource_types: list[str]
    policy_status: str
    cdn_status: str
    first: list[ResourceSample]
    second: list[ResourceSample]

    def to_dict(self) -> dict:
        return {
            "url": self.url,
            "hostname": self.hostname,
            "pages": self.pages,
            "profiles": self.profiles,
            "resourceTypes": self.resource_types,
            "policyStatus": self.policy_status,
            "cdnStatus": self.cdn_status,
            "first": [sample.to_dict() for sample in self.first],
            "second": [sample.to_dict() for sample in self.second],
        }


def parse_positive_integer(value: str, allow_zero: bool = False) -> int:
    minimum = 0 if allow_zero else 1
    try:
        parsed = float(value)
    except ValueError as exc:
        raise ValueError(
            f"must be an integer greater than or equal to {minimum}"
        ) from exc
    if not parsed.is_integer() or parsed < minimum:
        raise ValueError(f"must be an integer greater than or equal to {minimum}")
    return int(parsed)


def _positive_int(value: str) -> int:
    try:
        return parse_positive_integer(value, allow_zero=False)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(str(exc)) from exc


def _non_negative_int(value: str) -> int:
    try:
        return parse_positive_integer(value, allow_zero=True)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(str(exc)) from exc


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Audit CDN cache behavior for same-origin pages."
    )
    parser.add_argument(
        "--base-url",
        default="https://gsgfs.moe/",
        help="Site origin to crawl (default: https://gsgfs.moe/)",
    )
    parser.add_argument("--sitemap-url", help="Sitemap or sitemap index URL")
    parser.add_argument("--output", help="Output prefix without .json/.csv")
    parser.add_argument(
        "--max-pages",
        type=_non_negative_int,
        default=500,
        help="Maximum pages per profile; 0 is unlimited (default: 500)",
    )
    parser.add_argument(
        "--timeout-ms",
        type=_positive_int,
        default=30_000,
        help="Navigation timeout (default: 30000)",
    )
    parser.add_argument(
        "--settle-ms",
        type=_non_negative_int,
        default=1_000,
        help="Wait after scrolling (default: 1000)",
    )
    parser.add_argument(
        "--scroll-delay-ms",
        type=_non_negative_int,
        default=150,
        help="Delay between scroll steps (default: 150)",
    )
    parser.add_argument(
        "--max-scrolls",
        type=_non_negative_int,
        default=40,
        help="Maximum scroll steps per page (default: 40)",
    )
    parser.add_argument(
        "--delay-ms",
        type=_non_negative_int,
        default=100,
        help="Delay between page visits (default: 100)",
    )
    parser.add_argument(
        "--profile",
        action="append",
        choices=("desktop", "mobile"),
        default=[],
        help="Browser profile; repeatable (default: both)",
    )
    parser.add_argument(
        "--resource-host",
        action="append",
        default=[],
        help="Host to audit; repeatable",
    )
    parser.add_argument(
        "--exclude-path-prefix",
        action="append",
        default=[],
        help="Additional same-origin path prefix to skip",
    )
    parser.add_argument(
        "--storage-state",
        help="Playwright storage state for authenticated pages",
    )
    parser.add_argument(
        "--fail-on-issues",
        action="store_true",
        help="Exit 2 when policy or CDN issues are found",
    )
    return parser


def parse_arguments(argv: Sequence[str] | None = None) -> AuditOptions:
    parser = _build_parser()
    args = parser.parse_args(argv)

    options = AuditOptions(
        base_url=args.base_url,
        sitemap_url=args.sitemap_url,
        output=args.output,
        max_pages=args.max_pages,
        timeout_ms=args.timeout_ms,
        settle_ms=args.settle_ms,
        scroll_delay_ms=args.scroll_delay_ms,
        max_scrolls=args.max_scrolls,
        delay_ms=args.delay_ms,
        profiles=list(args.profile),
        resource_hosts=[host.lower() for host in args.resource_host],
        excluded_prefixes=[*DEFAULT_EXCLUDED_PREFIXES, *args.exclude_path_prefix],
        storage_state=args.storage_state,
        fail_on_issues=args.fail_on_issues,
    )

    base_parts = urlsplit(options.base_url)
    path = base_parts.path or "/"
    if not path.endswith("/"):
        path += "/"
    base_parts = base_parts._replace(path=path, fragment="")
    options.base_url = _canonical_url(base_parts)

    if options.sitemap_url is None:
        sitemap_url = _absolute_url("sitemap.xml", options.base_url)
    else:
        sitemap_url = _absolute_url(options.sitemap_url, options.base_url)
    options.sitemap_url = _canonical_url(urlsplit(sitemap_url))

    if not options.resource_hosts:
        options.resource_hosts = list(DEFAULT_RESOURCE_HOSTS)
    else:
        options.resource_hosts = list(dict.fromkeys(options.resource_hosts))

    if not options.profiles:
        options.profiles = ["desktop", "mobile"]
    else:
        options.profiles = list(dict.fromkeys(options.profiles))

    options.resource_host_set = set(options.resource_hosts)
    return options


def _absolute_url(candidate: str, base_url: str) -> str:
    return urljoin(base_url, candidate)


def decode_xml(value: str) -> str:
    return (
        value.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", '"')
        .replace("&apos;", "'")
    )


def parse_sitemap_locations(xml: str) -> list[str]:
    return [
        decode_xml(match.strip())
        for match in re.findall(r"<loc\b[^>]*>([\s\S]*?)</loc>", xml, re.IGNORECASE)
    ]


def _normalize_prefix(prefix: str) -> str:
    normalized = prefix if prefix.startswith("/") else f"/{prefix}"
    return normalized[:-1] if normalized.endswith("/") else normalized


def has_excluded_prefix(pathname: str, prefixes: list[str]) -> bool:
    return any(
        pathname == _normalize_prefix(prefix)
        or pathname.startswith(f"{_normalize_prefix(prefix)}/")
        for prefix in prefixes
    )


def _origin(url) -> str:
    scheme = url.scheme.lower()
    hostname = (url.hostname or "").lower()
    port = url.port
    default_port = {"http": 80, "https": 443}.get(scheme)
    if port == default_port:
        port = None
    if port is None:
        return f"{scheme}://{hostname}"
    return f"{scheme}://{hostname}:{port}"


def _canonical_url(url) -> str:
    scheme = url.scheme.lower()
    hostname = (url.hostname or "").lower()
    if ":" in hostname and not hostname.startswith("["):
        hostname = f"[{hostname}]"
    port = url.port
    default_port = {"http": 80, "https": 443}.get(scheme)
    if port == default_port:
        port = None
    userinfo = ""
    if "@" in url.netloc:
        userinfo = f"{url.netloc.rsplit('@', 1)[0]}@"
    netloc = userinfo + hostname
    if port is not None:
        netloc = f"{netloc}:{port}"
    path = quote((url.path or "/").replace("\\", "/"), safe=_URL_PATH_SAFE)
    if not path.startswith("/"):
        path = f"/{path}"
    query = quote(url.query or "", safe=_URL_QUERY_SAFE)
    return urlunsplit((scheme, netloc, path, query, url.fragment))


def _normalize_query(query: str) -> str:
    params = parse_qsl(query, keep_blank_values=True)
    params = [
        (name, value)
        for name, value in params
        if not name.startswith("utm_") and name not in ("fbclid", "gclid")
    ]
    params.sort(key=lambda item: item[0])
    return urlencode(params)


def normalize_page_url(
    candidate: str,
    base_url: str,
    excluded_prefixes: list[str] | None = None,
) -> str | None:
    if excluded_prefixes is None:
        excluded_prefixes = list(DEFAULT_EXCLUDED_PREFIXES)
    try:
        url = urlsplit(_absolute_url(candidate, base_url))
    except ValueError:
        return None

    base = urlsplit(base_url)
    try:
        if url.scheme.lower() not in ("http", "https") or _origin(url) != _origin(base):
            return None

        url = url._replace(
            path=url.path or "/",
            fragment="",
            query=_normalize_query(url.query),
        )

        if url.path in DEFAULT_EXCLUDED_PATHS or has_excluded_prefix(
            url.path, excluded_prefixes
        ):
            return None

        return _canonical_url(url)
    except ValueError:
        return None


def discover_sitemap_urls(
    sitemap_url: str,
    base_url: str,
    excluded_prefixes: list[str],
    errors: list[dict],
) -> set[str]:
    import requests

    pages: set[str] = set()
    pending = [sitemap_url]
    visited: set[str] = set()

    while pending and len(visited) < 100:
        current = pending.pop(0)
        if current in visited:
            continue
        visited.add(current)

        try:
            response = requests.get(
                current,
                headers={"user-agent": "gsgfs-cdn-cache-audit/1.0"},
                timeout=30,
            )
            response.raise_for_status()
            xml = response.text
            locations = parse_sitemap_locations(xml)
            if re.search(r"<sitemapindex\b", xml, re.IGNORECASE):
                pending.extend(locations)
                continue
            for location in locations:
                normalized = normalize_page_url(location, base_url, excluded_prefixes)
                if normalized:
                    pages.add(normalized)
        except Exception as error:
            errors.append({"url": current, "error": str(error)})

    return pages


def profile_options(playwright, profile: str) -> dict:
    if profile == "mobile":
        return playwright.devices["Pixel 10"]
    return playwright.devices["Desktop Chrome"]


@contextmanager
def browser_context(
    playwright, browser, profile: str, options: AuditOptions
) -> Iterator:
    context_options = dict(profile_options(playwright, profile))
    context_options["service_workers"] = "block"
    if options.storage_state is not None:
        context_options["storage_state"] = options.storage_state
    context = browser.new_context(**context_options)
    try:
        yield context
    finally:
        context.close()


@contextmanager
def browser_session() -> Iterator:
    from playwright.sync_api import sync_playwright

    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True)
        try:
            yield playwright, browser
        finally:
            browser.close()


def disable_browser_cache(context, page):
    session = context.new_cdp_session(page)
    session.send("Network.enable")
    session.send("Network.setCacheDisabled", {"cacheDisabled": True})
    return session


def scroll_page(page, max_scrolls: int, scroll_delay_ms: int) -> None:
    if max_scrolls == 0:
        return
    page.evaluate(
        """async ({ limit, delay }) => {
            const wait = (milliseconds) =>
                new Promise((resolve) => setTimeout(resolve, milliseconds));
            let previousHeight = 0;
            let stableAtBottom = 0;
            for (let index = 0; index < limit; index += 1) {
                const height = Math.max(
                    document.body.scrollHeight,
                    document.documentElement.scrollHeight,
                );
                const nextTop = Math.min(
                    window.scrollY + window.innerHeight * 0.8,
                    height,
                );
                window.scrollTo({ top: nextTop, behavior: "instant" });
                await wait(delay);
                const atBottom = window.scrollY + window.innerHeight >= height - 2;
                if (atBottom && height === previousHeight) {
                    stableAtBottom += 1;
                    if (stableAtBottom >= 2) {
                        break;
                    }
                } else {
                    stableAtBottom = 0;
                }
                previousHeight = height;
            }
        }""",
        {"limit": max_scrolls, "delay": scroll_delay_ms},
    )


def scan_page(
    context, url: str, profile: str, pass_number: int, options: AuditOptions
) -> PageScan:
    page = context.new_page()
    session = disable_browser_cache(context, page)
    resources: list[ResourceSample] = []
    page_errors: list[str] = []
    document_status = None
    document_content_type = None

    def on_pageerror(error):
        page_errors.append(str(error))

    def on_response(response):
        request = response.request
        if request.method != "GET":
            return
        try:
            resource_url = urlsplit(response.url)
        except ValueError:
            return
        if (resource_url.hostname or "").lower() not in options.resource_host_set:
            return

        headers = response.headers
        resources.append(
            ResourceSample(
                url=response.url,
                page_url=url,
                profile=profile,
                pass_number=pass_number,
                resource_type=request.resource_type,
                http_status=response.status,
                cache_control=headers.get("cache-control"),
                cf_cache_status=(headers.get("cf-cache-status") or "").upper() or None,
                age=headers.get("age"),
                cf_ray=headers.get("cf-ray"),
                content_type=headers.get("content-type"),
                from_service_worker=response.from_service_worker,
            )
        )

    page.on("pageerror", on_pageerror)
    page.on("response", on_response)

    try:
        response = page.goto(
            url, wait_until="domcontentloaded", timeout=options.timeout_ms
        )
        if response is not None:
            document_status = response.status
            document_content_type = response.headers.get("content-type")
        page.wait_for_timeout(min(options.settle_ms, 500))
        scroll_page(page, options.max_scrolls, options.scroll_delay_ms)
        page.wait_for_timeout(options.settle_ms)
    except Exception as error:
        page_errors.append(str(error))

    links: list[str] = []
    if (
        document_content_type is not None
        and "text/html" in document_content_type.lower()
    ):
        try:
            links = page.locator("a[href]").evaluate_all(
                "(anchors) => anchors.map((anchor) => anchor.href).filter(Boolean)"
            )
        except Exception as error:
            page_errors.append(str(error))

    session.detach()
    page.close()

    return PageScan(
        page=PageResult(
            url=url,
            profile=profile,
            pass_number=pass_number,
            status=document_status,
            content_type=document_content_type,
            errors=page_errors,
        ),
        links=links,
        resources=resources,
    )


def pause(milliseconds: int) -> None:
    import time

    if milliseconds > 0:
        time.sleep(milliseconds / 1000)


def scan_discovery_pass(
    playwright,
    browser,
    seed_urls: list[str],
    profile: str,
    options: AuditOptions,
) -> DiscoveryResult:
    with browser_context(playwright, browser, profile, options) as context:
        queue = list(seed_urls)
        queued = set(queue)
        visited: list[str] = []
        page_results: list[PageResult] = []
        resources: list[ResourceSample] = []
        limit = float("inf") if options.max_pages == 0 else options.max_pages

        while queue and len(visited) < limit:
            url = queue.pop(0)
            logger.info("[pass 1/%s] %s: %s", profile, len(visited) + 1, url)
            result = scan_page(context, url, profile, 1, options)
            visited.append(url)
            page_results.append(result.page)
            resources.extend(result.resources)

            for link in result.links:
                normalized = normalize_page_url(
                    link, options.base_url, options.excluded_prefixes
                )
                if normalized and normalized not in queued:
                    queued.add(normalized)
                    queue.append(normalized)
            pause(options.delay_ms)

    return DiscoveryResult(
        visited=visited, page_results=page_results, resources=resources
    )


def scan_verification_pass(
    playwright,
    browser,
    urls: list[str],
    profile: str,
    options: AuditOptions,
) -> VerificationResult:
    with browser_context(playwright, browser, profile, options) as context:
        page_results: list[PageResult] = []
        resources: list[ResourceSample] = []

        for index, url in enumerate(urls, start=1):
            logger.info("[pass 2/%s] %s/%s: %s", profile, index, len(urls), url)
            result = scan_page(context, url, profile, 2, options)
            page_results.append(result.page)
            resources.extend(result.resources)
            pause(options.delay_ms)

    return VerificationResult(page_results=page_results, resources=resources)


def unique_values(samples: Sequence[dict], name: str) -> list:
    return list(
        dict.fromkeys(
            sample[name] for sample in samples if sample.get(name) is not None
        )
    )


def ray_colo(ray: str | None) -> str | None:
    if not ray:
        return None
    return ray.split("-")[-1].upper()


def classify_samples(first: Sequence[dict], second: Sequence[dict]) -> dict:
    successful = [
        sample
        for sample in [*first, *second]
        if sample.get("httpStatus") is not None and 200 <= sample["httpStatus"] < 400
    ]
    samples_with_control = [
        sample for sample in successful if sample.get("cacheControl") is not None
    ]
    controls = unique_values(successful, "cacheControl")
    policy_status = "unknown"

    if successful and not controls:
        policy_status = "missing"
    elif samples_with_control and len(samples_with_control) < len(successful):
        policy_status = "inconsistent"
    elif any(
        re.search(r"(?:^|,)\s*(?:private|no-store)(?:\s|,|$)", value, re.IGNORECASE)
        for value in controls
    ):
        policy_status = "non-cacheable"
    elif any(
        re.search(r"(?:s-maxage|max-age)\s*=\s*0\b", value, re.IGNORECASE)
        for value in controls
    ):
        policy_status = "zero-ttl"
    elif any(
        re.search(r"(?:^|,)\s*no-cache(?:\s|,|$)", value, re.IGNORECASE)
        for value in controls
    ):
        policy_status = "revalidate"
    elif controls:
        policy_status = "explicit"

    first_statuses = unique_values(first, "cfCacheStatus")
    second_statuses = unique_values(second, "cfCacheStatus")
    all_statuses = [*first_statuses, *second_statuses]
    cdn_status = "unknown"

    if len(second) == 0:
        cdn_status = (
            "cached-not-retested"
            if any(status in CACHED_STATUSES for status in all_statuses)
            else "not-retested"
        )
    elif len(second_statuses) > 1 and not set(second_statuses) <= CACHED_STATUSES:
        cdn_status = "inconsistent"
    elif any(status in CACHED_STATUSES for status in second_statuses):
        cdn_status = "cached"
    elif "BYPASS" in second_statuses:
        cdn_status = "bypass"
    elif "DYNAMIC" in second_statuses:
        cdn_status = "dynamic"
    elif len(second_statuses) == 1 and second_statuses[0] == "MISS":
        first_colos = {
            ray_colo(sample.get("cfRay"))
            for sample in first
            if ray_colo(sample.get("cfRay"))
        }
        second_colos = {
            ray_colo(sample.get("cfRay"))
            for sample in second
            if ray_colo(sample.get("cfRay"))
        }
        same_colo = any(colo in first_colos for colo in second_colos)
        cdn_status = (
            "repeated-miss" if "MISS" in first_statuses and same_colo else "miss"
        )
    elif second_statuses:
        cdn_status = "+".join(status.lower() for status in second_statuses)

    return {"policyStatus": policy_status, "cdnStatus": cdn_status}


def aggregate_resources(samples: Sequence[ResourceSample]) -> list[AggregatedResource]:
    grouped: dict[str, dict] = {}

    for sample in samples:
        entry = grouped.setdefault(
            sample.url,
            {
                "pages": set(),
                "profiles": set(),
                "resourceTypes": set(),
                "first": [],
                "second": [],
            },
        )
        entry["pages"].add(sample.page_url)
        entry["profiles"].add(sample.profile)
        entry["resourceTypes"].add(sample.resource_type)
        entry["first" if sample.pass_number == 1 else "second"].append(sample)

    resources: list[AggregatedResource] = []
    for url, entry in grouped.items():
        first = entry["first"]
        second = entry["second"]
        classified = classify_samples(
            [sample.to_dict() for sample in first],
            [sample.to_dict() for sample in second],
        )
        resources.append(
            AggregatedResource(
                url=url,
                hostname=urlsplit(url).hostname,
                pages=sorted(entry["pages"]),
                profiles=sorted(entry["profiles"]),
                resource_types=sorted(entry["resourceTypes"]),
                policy_status=classified["policyStatus"],
                cdn_status=classified["cdnStatus"],
                first=first,
                second=second,
            )
        )

    resources.sort(key=lambda resource: resource.url)
    return resources


def csv_cell(value) -> str:
    text = "" if value is None else str(value)
    if re.search(r'[",\r\n]', text):
        return f'"{text.replace(chr(34), chr(34) * 2)}"'
    return text


def _resource_dict(resource: AggregatedResource | dict) -> dict:
    return resource.to_dict() if isinstance(resource, AggregatedResource) else resource


def to_csv(resources: Sequence[AggregatedResource | dict]) -> str:
    columns = [
        "policy_status",
        "cdn_status",
        "url",
        "hostname",
        "resource_types",
        "profiles",
        "page_count",
        "pages",
        "first_http_status",
        "first_cache_control",
        "first_cf_cache_status",
        "first_age",
        "first_cf_ray",
        "second_http_status",
        "second_cache_control",
        "second_cf_cache_status",
        "second_age",
        "second_cf_ray",
    ]

    def joined(samples, field):
        return "|".join(str(value) for value in unique_values(samples, field))

    rows = []
    for resource in resources:
        data = _resource_dict(resource)
        rows.append(
            [
                data["policyStatus"],
                data["cdnStatus"],
                data["url"],
                data["hostname"],
                "|".join(data["resourceTypes"]),
                "|".join(data["profiles"]),
                len(data["pages"]),
                " ".join(data["pages"]),
                joined(data["first"], "httpStatus"),
                joined(data["first"], "cacheControl"),
                joined(data["first"], "cfCacheStatus"),
                joined(data["first"], "age"),
                joined(data["first"], "cfRay"),
                joined(data["second"], "httpStatus"),
                joined(data["second"], "cacheControl"),
                joined(data["second"], "cfCacheStatus"),
                joined(data["second"], "age"),
                joined(data["second"], "cfRay"),
            ]
        )

    lines = [",".join(csv_cell(value) for value in row) for row in [columns, *rows]]
    return "\n".join(lines) + "\n"


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def default_output_prefix() -> str:
    return f"artifacts/cdn-cache-audit-{_utc_now_iso()}"


def summarize(
    resources: Sequence[AggregatedResource | dict],
    pages: Sequence[PageResult | dict],
    sitemap_errors: Sequence[dict],
) -> dict:
    def counts(field: str) -> dict:
        values = sorted({_resource_dict(r)[field] for r in resources})
        return {
            value: sum(1 for r in resources if _resource_dict(r)[field] == value)
            for value in values
        }

    return {
        "pagesScanned": len({_page_dict(p)["url"] for p in pages}),
        "pageVisits": len(pages),
        "pageErrors": sum(1 for p in pages if _page_dict(p)["errors"]),
        "sitemapErrors": len(sitemap_errors),
        "resources": len(resources),
        "policyStatus": counts("policyStatus"),
        "cdnStatus": counts("cdnStatus"),
    }


def _page_dict(page: PageResult | dict) -> dict:
    return page.to_dict() if isinstance(page, PageResult) else page


def has_issues(resource: AggregatedResource | dict) -> bool:
    data = _resource_dict(resource)
    return data["policyStatus"] != "explicit" or data["cdnStatus"] != "cached"


def audit_has_issues(
    resources: Sequence[AggregatedResource | dict],
    pages: Sequence[PageResult | dict],
    sitemap_errors: Sequence[dict],
) -> bool:
    if sitemap_errors or not pages or not resources:
        return True
    if any(
        _page_dict(page)["errors"]
        or _page_dict(page)["status"] is None
        or not 200 <= _page_dict(page)["status"] < 400
        for page in pages
    ):
        return True
    return any(has_issues(resource) for resource in resources)


def run(options: AuditOptions) -> bool:
    sitemap_errors: list[dict] = []
    sitemap_url = options.sitemap_url or _absolute_url("sitemap.xml", options.base_url)
    sitemap_pages = discover_sitemap_urls(
        sitemap_url,
        options.base_url,
        options.excluded_prefixes,
        sitemap_errors,
    )
    base_page = normalize_page_url(
        options.base_url, options.base_url, options.excluded_prefixes
    )
    seeds = {base_page} if base_page else set()
    seeds.update(sitemap_pages)

    page_results: list[PageResult] = []
    samples: list[ResourceSample] = []
    pages_by_profile: dict[str, list[str]] = {}

    with browser_session() as (playwright, browser):
        for profile in options.profiles:
            first = scan_discovery_pass(
                playwright, browser, list(seeds), profile, options
            )
            pages_by_profile[profile] = first.visited
            page_results.extend(first.page_results)
            samples.extend(first.resources)
        for profile in options.profiles:
            second = scan_verification_pass(
                playwright, browser, pages_by_profile[profile], profile, options
            )
            page_results.extend(second.page_results)
            samples.extend(second.resources)

    resources = aggregate_resources(samples)
    summary = summarize(resources, page_results, sitemap_errors)
    output_prefix = Path(options.output or default_output_prefix()).resolve()
    output_prefix.parent.mkdir(parents=True, exist_ok=True)
    report = {
        "generatedAt": _utc_now_iso(),
        "config": {
            "baseUrl": options.base_url,
            "sitemapUrl": options.sitemap_url,
            "resourceHosts": options.resource_hosts,
            "profiles": options.profiles,
            "maxPages": options.max_pages,
        },
        "summary": summary,
        "sitemapErrors": sitemap_errors,
        "pages": [page.to_dict() for page in page_results],
        "resources": [resource.to_dict() for resource in resources],
    }
    (output_prefix.parent / f"{output_prefix.name}.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (output_prefix.parent / f"{output_prefix.name}.csv").write_text(
        to_csv(resources),
        encoding="utf-8",
    )

    sys.stdout.write(json.dumps(summary, indent=2, ensure_ascii=False) + "\n")
    sys.stdout.write(f"JSON: {output_prefix}.json\nCSV:  {output_prefix}.csv\n")
    return options.fail_on_issues and audit_has_issues(
        resources, page_results, sitemap_errors
    )


def main() -> None:
    logging.basicConfig(level=logging.INFO, stream=sys.stderr, format="%(message)s")
    try:
        options = parse_arguments()
        if run(options):
            sys.exit(2)
    except Exception:
        logger.exception("unexpected error")
        sys.exit(1)


if __name__ == "__main__":
    main()
