depends_on:
  - build

when:
  - event: [push, manual]
    branch: [main, woodpecker-test]

concurrency: 1

steps:
  - name: update-kustomize
    image: docker.io/library/archlinux:latest
    environment:
      GITOPS_SSH_KEY:
        from_secret: GITOPS_SSH_KEY
      FORGEJO_KNOWN_HOSTS:
        from_secret: FORGEJO_KNOWN_HOSTS
      REGISTRY_DOMAIN:
        from_secret: REGISTRY_DOMAIN
      GITOPS_REPO_URL: ssh://git@forgejo-ssh.forgejo.svc.cluster.local/GSGFs/blog.git
    commands:
      # install dependencies
      - pacman -Syu kustomize git openssh --noconfirm
      # config ssh
      - install -d -m 700 ~/.ssh
      - printf '%s\n' "$GITOPS_SSH_KEY" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - printf '%s\n' "$FORGEJO_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      # config git
      - git config user.email "woodpecker-bot@git.gsgfs.sh"
      - git config user.name "Woodpecker CI"
      - git remote remove gitops 2>/dev/null || true
      - git remote add gitops "$GITOPS_REPO_URL"
      # update kustomization
      - cd .config/k8s/overlays/prod
      - kustomize edit set image blog-app=$REGISTRY_DOMAIN/blog-app:${CI_COMMIT_SHA}
      - kustomize edit set image blog-backup=$REGISTRY_DOMAIN/blog-backup:${CI_COMMIT_SHA}
      - kustomize edit set image blog-model-downloader=$REGISTRY_DOMAIN/blog-model-downloader:${CI_COMMIT_SHA}
      - kustomize edit set image blog-pgbouncer=$REGISTRY_DOMAIN/blog-pgbouncer:${CI_COMMIT_SHA}
      # push
      - git add kustomization.yaml
      - |
        if ! git diff --cached --quiet; then
          git commit -m "chore(gitops): update image tags to ${CI_COMMIT_SHA:0:7} [skip ci]"
          git push gitops HEAD:${CI_COMMIT_BRANCH}
        else
          echo "No changes to commit"
        fi
