depends_on:
  - build

when:
  - event: [push, manual]
    branch: [main, woodpecker-test]

steps:
  - name: update-kustomize
    image: docker.io/library/archlinux:latest
    environment:
      GITOPS_TOKEN:
        from_secret: GITOPS_TOKEN
      REGISTRY_DOMAIN:
        from_secret: REGISTRY_DOMAIN
    commands:
      - pacman -Sy --noconfirm
      - pacman -S kustomize git openssh --noconfirm
      # Setup SSH
      - mkdir -p ~/.ssh
      - echo "$GITOPS_TOKEN" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
      # set git config
      - git config --global user.email "woodpecker-bot@local"
      - git config --global user.name "Woodpecker CI"
      - git remote set-url origin git@codeberg.org:GSGFs7/blog.git
      # update kustomize
      - cd .config/k8s/overlays/prod
      - kustomize edit set image blog-app=$REGISTRY_DOMAIN/blog-app:${CI_COMMIT_SHA}
      - kustomize edit set image blog-backup=$REGISTRY_DOMAIN/blog-backup:${CI_COMMIT_SHA}
      - kustomize edit set image blog-model-downloader=$REGISTRY_DOMAIN/blog-model-downloader:${CI_COMMIT_SHA}
      # commit and push
      - git add kustomization.yaml
      - |
        if ! git diff --cached --quiet; then
          git commit -m "chore(gitops): update image tags to ${CI_COMMIT_SHA:0:7} [skip ci]"
          git push origin HEAD:${CI_COMMIT_BRANCH}
        else
          echo "No changes to commit"
        fi
