labels:
  scaner: "true"

when:
  - event: [push, pull_request, manual]
    branch:
      - main
      - woodpecker-test
      - dev

services:
  db:
    image: docker.io/pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_DB: woodpecker_test
      POSTGRES_USER: woodpecker_test_user
      POSTGRES_PASSWORD: woodpecker_test_passwd
  redis:
    image: docker.io/library/redis:8-alpine

steps:
  - name: test
    image: docker.io/library/archlinux:latest
    environment:
      DEBUG: "True"
      APP_BUILD_ID: test
      DJANGO_SECRET_KEY: woodpecker_test_django_secret_key
      FERNET_KEY: MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=
      DATABASE_ENGINE: postgresql
      DATABASE_NAME: woodpecker_test
      DATABASE_USER: woodpecker_test_user
      DATABASE_PASSWORD: woodpecker_test_passwd
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      USE_REMOTE_EMBEDDING: "True"
      REMOTE_EMBEDDING_API_BASE:
        from_secret: EMBEDDING_API_BASE
      REMOTE_EMBEDDING_API_KEY:
        from_secret: EMBEDDING_API_KEY
      REMOTE_EMBEDDING_MODEL_NAME: embeddinggemma-300m
      UV_VENV_COPY: "1"
      UV_LINK_MODE: "copy"
    commands:
      # env setup
      - pacman -Syu base-devel uv git python perl-image-exiftool nodejs pnpm chromium firefox --noconfirm
      - ln -s /usr/bin/vendor_perl/exiftool /usr/bin/exiftool # fix exiftool path
      - pnpm install --frozen-lockfile
      - pnpm exec playwright install
      - uv sync --frozen

      # static analysis
      - uv run ruff check .
      - uv run ruff format --check .
      - pnpm run fmt:check
      - pnpm run typecheck
      - pnpm run lint

      # database setup
      - uv run manage.py migrate
      - uv run manage.py makemigrations --check --dry-run

      # build and unit tests
      - pnpm run build:all
      - pnpm run test --coverage
      - uv run python -W default -m coverage run manage.py test -v 2
      - uv run coverage xml -i

      # e2e tests
      - pnpm run test:e2e:base:htmx
      - pnpm run test:e2e:htmx
      - pnpm run test:e2e:base:native
      - pnpm run test:e2e:native
      - E2E_SUITE=ssr pnpm exec playwright test

  - name: scan
    image: sonarsource/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_HOST_URL: https://sonarqube.gsgfs.sh
    commands:
      - sonar-scanner -Dproject.settings=.config/sonar/sonar-project.properties
    when:
      - branch: [main]
        event: [push, pull_request, manual]
